server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3311/edsp_test?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: edspuser
    password: ccmedia
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    show-sql: true